import type { TemplateDefinition } from '../types/template'

export const featureDemoTemplate: TemplateDefinition = {
  id: 'builtin-feature-demo',
  name: { en: 'Feature Demo', zh: '功能演示' },
  builtin: true,
  version: 1,
  layout: {
    aspectRatio: { mode: 'fixed', ratio: [1, 1] },
    padding: { top: 0.1, right: 0.1, bottom: 0.1, left: 0.1 },
    imageCornerRadius: 0.05,
    imageOpacity: 0.84,
    frameColor: { type: 'auto', source: 'swatch', swatchRole: 'DarkMuted', opacity: 1 },
    crop: null,
  },
  elements: [
    {
      type: 'text',
      id: 'minimal-camera',
      content: '自动取色会根据照片动态调整',
      style: {
        blendMode: 'difference',
        fontFamily: 'ZCOOL XiaoWei',
        fontSize: 0.03,
        fontWeight: 500,
        color: { type: 'fixed', value: '#FFFFFF', opacity: 1 },
        letterSpacing: 0,
        lineHeight: 1,
      },
      position: { x: -0.5, y: -0.5 },
      align: 'left',
      verticalAlign: 'bottom',
    },
    {
      type: 'text',
      id: 'uRU1CS2QqQ5vnIq4yUbAQ',
      content: '单击文字跳转编辑\n支持拖动自动对齐',
      style: {
        fontFamily: 'Ma Shan Zheng',
        fontSize: 0.05,
        fontWeight: 500,
        color: { type: 'fixed', value: '#FFFFFF', opacity: 1 },
        letterSpacing: 0,
        lineHeight: 1,
        blendMode: 'normal',
      },
      position: { x: 0, y: 0 },
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'TFueqvYp8-zaOr-yx2SQf',
      content: '插入信息会动态渲染如拍摄日期：{{date}}',
      style: {
        fontFamily: 'LXGW WenKai TC',
        fontSize: 0.03,
        fontWeight: 700,
        color: { type: 'fixed', value: '#FFFFFF', opacity: 1 },
        letterSpacing: 0,
        lineHeight: 1,
        blendMode: 'difference',
      },
      position: { x: 0.5, y: 0.5 },
      align: 'right',
      verticalAlign: 'top',
    },
  ],
}
