import type { TemplateDefinition } from '../types/template'

export const polaroidTemplate: TemplateDefinition = {
  id: 'builtin-polaroid',
  name: { en: 'Polaroid', zh: '拍立得' },
  builtin: true,
  version: 1,
  layout: {
    aspectRatio: { mode: 'original' },
    padding: { top: 0.06, right: 0.06, bottom: 0.20, left: 0.06 },
    imageCornerRadius: 0,
    imageOpacity: 1,
    frameColor: { type: 'fixed', value: '#FFFFFF', opacity: 1 },
  },
  elements: [
    {
      type: 'text',
      id: 'polaroid-camera',
      content: '{{exif.model}}',
      style: {
        fontFamily: 'JetBrains Mono',
        fontSize: 0.028,
        fontWeight: 500,
        color: { type: 'fixed', value: '#2D2B2A', opacity: 0.85 },
        letterSpacing: 0.02,
        lineHeight: 1.4,
      },
      position: { x: 0, y: 0.38 },
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'polaroid-params',
      content: '{{exif.focalLength}}  {{exif.fNumber}}  {{exif.iso}}',
      style: {
        fontFamily: 'JetBrains Mono',
        fontSize: 0.022,
        fontWeight: 400,
        color: { type: 'fixed', value: '#2D2B2A', opacity: 0.6 },
        letterSpacing: 0.05,
        lineHeight: 1.4,
      },
      position: { x: 0, y: 0.43 },
      align: 'center',
      verticalAlign: 'middle',
    },
    {
      type: 'text',
      id: 'polaroid-date',
      content: '{{exif.date}}',
      style: {
        fontFamily: 'Instrument Serif',
        fontSize: 0.035,
        fontWeight: 400,
        color: { type: 'fixed', value: '#2D2B2A', opacity: 0.7 },
        letterSpacing: 0.02,
        lineHeight: 1.4,
      },
      position: { x: 0, y: 0.48 },
      align: 'center',
      verticalAlign: 'middle',
    },
  ],
}
